version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: smart-mock-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: serve

  smart-mock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-mock-server
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.1:8b
      - OLLAMA_TEMPERATURE=0.2
      - LOG_LEVEL=INFO
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data: