spring:
  application:
    name: smart-mock

server:
  port: 8080

# Project info from Maven (injected at build time)
app:
  version: @project.version@
  name: @project.name@
  description: @project.description@
  dependencies:
    spring-boot: @spring-boot.version@
    langchain4j: @langchain4j.version@
    caffeine: @caffeine.version@
    swagger-parser: @swagger-parser.version@
    json-schema-validator: @json-schema-validator.version@
  java:
    version: 21
    source: 21

ollama:
  base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
  model-name: ${OLLAMA_MODEL:codellama:7b}
  temperature: ${OLLAMA_TEMPERATURE:0.7}
  timeout: ${OLLAMA_TIMEOUT:60}

logging:
  level:
    ca.bazlur.smartmock: ${LOG_LEVEL:INFO}
    dev.langchain4j: ${LANGCHAIN_LOG_LEVEL:INFO}
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

cache:
  max-size: ${CACHE_MAX_SIZE:1000}
  expire-minutes: ${CACHE_EXPIRE_MINUTES:15}

# Storage Configuration
smart-mock:
  storage:
    enabled: ${STORAGE_ENABLED:true}
    path: ${STORAGE_PATH:${user.home}/.smart-mock/schemas}
  blocks:
    external:
      enabled: ${EXTERNAL_BLOCKS_ENABLED:true}
      path: ${EXTERNAL_BLOCKS_PATH:${user.home}/.smart-mock/blocks}

# Swagger UI Configuration
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /api-spec
  api-docs:
    enabled: true
    path: /v3/api-docs